### PR TITLE
Install/update charts indempotently

### PR DESCRIPTION
**Pull request by olblak**
Currently using helm::chart doesn't support chart update. 

According Helm documentation [docs.helm.sh](https://docs.helm.sh/developing_charts/#upgrade-a-release-idempotently), we can use `helm upgrade --install` (instead of `helm install`) to install/update charts.

Remark: Because I suggest to use another command for installing charts, this PR is not backward compatible (so don't merge it as is). 

Is this PR be benefit to this project?
Is it the right approach to suggest a change?

### CODE REVIEW

**Comment by olblak** [comment]
Would it be better to have a new resource helm::chart::update instead of updating helm::chart?

**Comment by olblak** [comment]
I created a new resource helm::chart_update and leave helm::chart as is.
I also update helm::helm_init to even run helm init when we use the paramater 'client_only'
Finally I updated helm to not create account config if we only want to run client_only

**Comment by aelbarkani** [comment]
Maybe I'm wrong, but I think there is a little problem with the idempotency since the helm upgrade command is not completely idempotent. 
I did not test your commit, but by reading your code I assume that the upgrade command will be executed no matter what. When doing that, helm increases the revision number, even if there is no change in the release. Of course, the final result will be the same, but still the increased revision number may be an issue.
A possible solution would be to not execute the command if the following three conditions are met:
- The chart is the same (name and version)
- The manifest is the same
- Helm upgrade is not invoked with --forced

In order to verify the two first conditions, you can perform a helm upgrade --dry run --debug and compare  its output with the output of helm get.

**Comment by davejrt** [comment]
LGTM

**Pull request merged**
