### PR TITLE
Actually run the tests

### PR DESCRIPTION
**Pull request by jaxxstorm**
First step in fixing #35

### CODE REVIEW

**Comment by jaxxstorm** [comment]
@davejrt @scotty-c any help here?

**Comment by davejrt** [comment]
@jaxxstorm rebase off master now and this should pass. There's been a lot of issues in the past 24 hours with upstream gems.

**Comment by jaxxstorm** [comment]
@davejrt this is still failing because of a the whole translate thing. Do we want to added the translate dependency here?

**Comment by davejrt** [comment]
LGTM

**Pull request merged**
