### PR TITLE
Add ability to deploy helm v3

### PR DESCRIPTION
**Pull request by AblionGE**
Update code to be able to deploy Helm v3

### CODE REVIEW

**Comment by AblionGE** [comment]
Hi @sheenaajay , any proposition how to better handle Helm v3 ?
Should I create new pp files for Helm v3 ? Totally replace Helm v2 by Helm v3 ? Or simply do "if" in the code (like I did) and clean what is deployed with Helm 3 (no more mention of tiller ?)

I'll continue with testing once I know in which direction we want to go.

**Comment by carabasdaniel** [comment]
Hi @AblionGE, thank you for your contribution. 

This draft looks really good.

I think for now we should keep the possibility to install either version, for now, so I believe some conditional logic should be added, as you already did, so please go ahead and prepare a couple of tests and we'll give it a try once the PR is ready for review.

**Comment by michaeltlombardi** [comment]
Since this hasn't seen any activity in over a month I'm going to go ahead and close this pull request for the time being. Please re-open this pull request once the next actions are addressed, new information is available, or you have a question related to this pull request. We've become aware of difficulties re-opening pull requests, in the event you cannot please mention `puppetlabs/modules` with an @ sign in front and we'll re-open this pull request.

Closing the pull request doesn't mean we don't consider this change valuable, just that there are things that need to be addressed before it can be merged. If you have any questions or concerns, please don't hesitate to ping us in slack.puppet.com.

**Comment by dramshaw-zymergen** [comment]
Where is helm 3 on the roadmap?

**Pull request closed without merging**
