### PR TITLE
Add support for Helm v3 (continued)

### PR DESCRIPTION
**Pull request by treydock**
@AblionGE and @daianamezdrea , this is a continuation of #129 but with some fixes.  The main fix is you can't reference class parameters in defined type parameter defaults without ensuring that those classes are defined before the defined type, which isn't always the best as it makes Puppet code dependent on the order things are defined. Instead you have to `include` the class and then reference the parameters.

Also had to rename the spec file for acceptance as usually rspec expects spec files to end with `_spec.rb`

Feel free to make my changes in #129 if that's preferable.

### CODE REVIEW

**Comment by AblionGE** [comment]
Thanks @treydock for improving this !

**Comment by treydock** [comment]
Updated pull request to simplify logic on avoiding `init` and other things when doing Helm v3 because those things are needed. For this most recent change the Puppet module was adding Kubernetes tiller resources like a ServiceAccount and that's not necessary with Helm v3 so this most recent change avoids unnecessary changes when install Helm v3, which should also reduce the diff size for entire pull request.

**Comment by daianamezdrea** [comment]
Hi @treydock, we have some dependency failures on ubuntu ( I'm currently working in solving the problem) and after this your PR will be tested on a clean base, thank you!

**Comment by daianamezdrea** [comment]
Hi @treydock, we added Github Actions for running our tests, can you rebase this PR? Thank you!

**Comment by treydock** [comment]
I have rebased

**Comment by treydock** [comment]
@daianamezdrea Is there a way to run integration tests outside Github Actions? Only 1 of the many tests failed and there is no useful output from the failure to tell me what went wrong so I'd like to test things locally but so far attempts to run the bolt commands locally has failed.

**Comment by daianamezdrea** [comment]
Hi @treydock, I was thinking at a way to get this tested and becaue the old way is not working anymore I have a suggestion that could help you:
1. Clone kream repo, which will help you to spin up a cluster on your Mac/Linux ---> https://github.com/puppetlabs/kream   
2. Follow the commands:
gem install bundler
bundle install
install kubectl (this needs to be applied according with your system)
3. install helm as here: https://github.com/puppetlabs/kream#helm
If you want to use your branch for helm version , go to Puppetfile and add your branch there, like this:
mod 'puppetlabs/helm', :git=> 'https://github.com/puppetlabs/puppetlabs-helm.git', :branch=> 'helm_test'

**Comment by daianamezdrea** [comment]
Please try this and let me know if it works, sorry for my late answer, I was trying to find a good solution for the problem and then I forgot about it, thank you!

**Pull request closed without merging**
