### PR TITLE
add username and password flags in helm_repo_add_flags

### PR DESCRIPTION
**Pull request by AblionGE**
Adding username/password to let the possibility to authenticate to an external helm repository.

### CODE REVIEW

**Comment by lionce** [comment]
Hello @AblionGE ,

Thank you for this contribution. Would it be possible to add some tests to verify that this is working as intended? 

Cheers.

**Comment by lionce** [comment]
Hello @AblionGE ,

Apparently the existing acceptance tests are  failing. Would you please rebase your branch with the latest code from master?

Thank you!

**Comment by AblionGE** [comment]
Hello @lionce ,
Rebase is done. For the tests, I can add some, but not in the next days... Will do my best :)
Thanks!

**Comment by AblionGE** [comment]
Hi @lionce and @sheenaajay , tests added. Please let me know if you need something else !

**Comment by sheenaajay** [comment]
@AblionGE Thank you for the changes. Running the adhoc tests.

**Comment by sheenaajay** [comment]
@AblionGE The tests failed with following error. Could you please check.

> Notice: Compiled catalog for dlmu74ujupsu3uy.delivery.puppetlabs.net in environment production in 0.13 seconds
12:03:20        	Info: Applying configuration version '1567767793'
12:03:20        	Notice: /Stage[main]/Main/Helm::Repo[myrepo]/Exec[helm repo myrepo]/returns: Error: unknown flag: --username
12:03:20        	Error: 'helm repo add --username 'myusername' --password 'mypassword' 'myrepo' 'https://raw.githubusercontent.com/sheenaajay/helmchart/master/charts/'' returned 1 instead of one of [0]
12:03:20        	Error: /Stage[main]/Main/Helm::Repo[myrepo]/Exec[helm repo myrepo]/returns: change from 'notrun' to ['0'] failed: 'helm repo add --username 'myusername' --password 'mypassword' 'myrepo' 'https://raw.githubusercontent.com/sheenaajay/helmchart/master/charts/'' returned 1 instead of one of [0]
12:03:20        	Notice: Applied catalog in 0.24 seconds
12:03:20        
12:03:20      # ./.bundle/gems/gems/beaker-4.12.0/lib/beaker/host.rb:391:in `exec'
12:03:20      # ./.bundle/gems/gems/beaker-4.12.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
12:03:20      # ./.bundle/gems/gems/beaker-4.12.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
12:03:20      # ./.bundle/gems/gems/beaker-4.12.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
12:03:20      # ./.bundle/gems/gems/beaker-4.12.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
12:03:20      # ./.bundle/gems/gems/beaker-puppet-1.18.7/lib/beaker-puppet/helpers/puppet_helpers.rb:529:in `block in apply_manifest_on'
12:03:20      # ./.bundle/gems/gems/beaker-4.12.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
12:03:20      # ./.bundle/gems/gems/beaker-4.12.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
12:03:20      # ./.bundle/gems/gems/beaker-puppet-1.18.7/lib/beaker-puppet/helpers/puppet_helpers.rb:457:in `apply_manifest_on'
12:03:20      # ./.bundle/gems/gems/beaker-puppet-1.18.7/lib/beaker-puppet/helpers/puppet_helpers.rb:536:in `apply_manifest'
12:03:20      # ./spec/acceptance/helm_spec.rb:139:in `block (4 levels) in <top (required)>'

**Comment by AblionGE** [comment]
@sheenaajay what version of helm are you using ?
I tried the command locally with my current helm version (v2.14.3) and I don't have the same problem. Nevertheless, I have an issue when using the username/password arguments. It seems that it doesn't like to have these arguments if the helm repo doesn't need them.

**Comment by sheenaajay** [comment]
@AblionGE I tried using the version v2.14.3 but looks like helm doesn't have the flags username and password. These are the supported flags for helm (https://helm.sh/docs/helm/)

> Flags:
      --debug                           enable verbose output
  -h, --help                            help for helm
      --home string                     location of your Helm config. Overrides $HELM_HOME (default "/root/.helm")
      --host string                     address of Tiller. Overrides $HELM_HOST
      --kube-context string             name of the kubeconfig context to use
      --kubeconfig string               absolute path to the kubeconfig file to use
      --tiller-connection-timeout int   the duration (in seconds) Helm will wait to establish a connection to tiller (default 300)
      --tiller-namespace string         namespace of Tiller (default "kube-system")

**Comment by AblionGE** [comment]
@sheenaajay , indeed helm doesn't have them, but "helm repo add" does: https://helm.sh/docs/helm/#helm-repo-add

>       --ca-file string     Verify certificates of HTTPS-enabled servers using this CA bundle
>       --cert-file string   Identify HTTPS client using this SSL certificate file
>       -h, --help               help for add
>       --key-file string    Identify HTTPS client using this SSL key file
>       --no-update          Raise error if repo is already registered
>       --password string    Chart repository password
>       --username string    Chart repository username

**Comment by sheenaajay** [comment]
@AblionGE Got it. Let me try to run the tests locally here , will let u know.PR looks good. Thank you.

**Comment by sheenaajay** [comment]
@AblionGE We can remove the acceptance tests for this change just unit tests will be fine.
Since we cant pass actual credentials to github?

**Comment by AblionGE** [comment]
@sheenaajay updated ;)

**Comment by sheenaajay** [comment]
Screen Shot 2019-09-17 at 08 47 25

**Comment by sheenaajay** [comment]
good work @AblionGE

**Pull request merged**
