### PR TITLE
Use subscribe instead of require to gain autoupdating

### PR DESCRIPTION
**Pull request by walkamongus**
Currently if yaml is updated, the new files are not applied.

### CODE REVIEW

**Comment by lionce** [comment]
Hello @walkamongus ,

Apparently the existing acceptance tests are failing. Your branch is behind master. Would you please rebase it with the current version of master? Thank you!

Cheers!

**Comment by walkamongus** [comment]
rebased onto master

**Comment by lionce** [comment]
close and reopen to rerun checks

**Comment by florindragos** [comment]
Hello @walkamongus, your branch still shows as being `22 commits behind puppetlabs:master.`

**Comment by walkamongus** [comment]
@florindragos rebased to catch up to `master`

**Pull request merged**
