### PR TITLE
Add ability to deploy helm v3

### PR DESCRIPTION
**Pull request by AblionGE**
fix tests

add unit test for helm_repo

removing helm 3 option in helm init

### CODE REVIEW

**Comment by AblionGE** [comment]
Hi,
I'm back with a new pull request for Helm 3 !
I was not able to run acceptance test due to a vagrant issue...

**Review by edomaur — APPROVED** [review]
Code seems to be clean, and testing deployment of helm3 seems to work as intended.

**Comment by daianamezdrea** [comment]
Hi @AblionGE ! Thank you for your PR, it looks very nice, IAC team has the Triage day on Monday when I will test your changes! Cheers!

**Comment by daianamezdrea** [comment]
Hi @AblionGE, I'm seeing this error on both centos7 and ubuntu 16.04 : 
`Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, 'split' parameter 'str' expects a String value, got Undef (file: /etc/puppetlabs/code/environments/production/modules/helm/manifests/repo.pp, line: 79, column: 18)`
I'm currently looking to see what is happening, thank  you for your patience !

**Comment by daianamezdrea** [comment]
Hi @AblionGE , we have some dependency failures on ubuntu ( I'm currently working in solving the problem) and after this your PR will be tested on a clean base, thank you!

**Comment by daianamezdrea** [comment]
Hi @AblionGE, we added Github Action for our tests, could you re-base your PR? Thank you!

**Comment by AblionGE** [comment]
Hello @daianamezdrea , Rebase done but integration testings are not passing. Is my rebase correct ?

**Comment by treydock** [comment]
I think this PR needs to be redone to fully remove Helm v2 support to simplify the module.  Helm v2 has long been EOL.

**Pull request closed without merging**
